# Generated by Django 3.2.6 on 2024-01-02 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_published_at'),
        ('blog', '0005_alter_post_slug'),
        ('blog', '0006_auto_20240101_1321'),
        ('blog', '0007_authorprofile'),
    ]

    operations = [
    ]
